type StatePickupAttribute = {
  stateName: string;
  mondayPickupTime: string;
  tuesdayPickupTime: string;
  wednesdayPickupTime: string;
  thursdayPickupTime: string;
  fridayPickupTime: string;
  saturdayPickupTime: string;
  sundayPickupTime: string;
};

const slotNone = '';
const slotHalfAM = '8:00 am - 2:00 pm';
const slotHalfPM = '2:00 am - 8:00 pm';
const slotFull = '8:00 am - 8:00 pm';

export const pickupStates: StatePickupAttribute[] = [
  {
    stateName: 'DIStrict of Columbia',
    mondayPickupTime: slotHalfPM,
    tuesdayPickupTime: slotHalfPM,
    wednesdayPickupTime: slotHalfPM,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotNone,
    sundayPickupTime: slotNone,
  },
  {
    stateName: 'Maryland',
    mondayPickupTime: slotHalfPM,
    tuesdayPickupTime: slotHalfPM,
    wednesdayPickupTime: slotHalfPM,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotNone,
    sundayPickupTime: slotNone,
  },
  {
    stateName: 'VIRGINIA',
    mondayPickupTime: slotHalfPM,
    tuesdayPickupTime: slotHalfPM,
    wednesdayPickupTime: slotHalfPM,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotNone,
    sundayPickupTime: slotNone,
  },
  {
    stateName: 'WEST VIRGINIA',
    mondayPickupTime: slotHalfPM,
    tuesdayPickupTime: slotHalfPM,
    wednesdayPickupTime: slotHalfPM,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotNone,
    sundayPickupTime: slotNone,
  },
  {
    stateName: 'DELAWARE',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotHalfPM,
    fridayPickupTime: slotHalfPM,
    saturdayPickupTime: slotNone,
    sundayPickupTime: slotNone,
  },

  {
    stateName: 'PENNSYLVANIA',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotHalfPM,
    fridayPickupTime: slotHalfPM,
    saturdayPickupTime: slotNone,
    sundayPickupTime: slotNone,
  },

  {
    stateName: 'NEW JERSEY',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotHalfPM,
    fridayPickupTime: slotHalfPM,
    saturdayPickupTime: slotNone,
    sundayPickupTime: slotNone,
  },
  {
    stateName: 'NEW YORK',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotHalfPM,
    fridayPickupTime: slotHalfPM,
    saturdayPickupTime: slotNone,
    sundayPickupTime: slotNone,
  },
  {
    stateName: 'KENTUCKY',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotFull,
    sundayPickupTime: slotFull,
  },

  {
    stateName: 'ILLINOIS',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotFull,
    sundayPickupTime: slotFull,
  },
  {
    stateName: 'INDIANA',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotFull,
    sundayPickupTime: slotFull,
  },
  {
    stateName: 'OHIO',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotFull,
    sundayPickupTime: slotFull,
  },

  {
    stateName: 'MICHIGAN',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotFull,
    sundayPickupTime: slotFull,
  },
  {
    stateName: 'WISCONSIN',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotFull,
    sundayPickupTime: slotFull,
  },

  {
    stateName: 'MINNESOTA',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotFull,
    sundayPickupTime: slotFull,
  },

  {
    stateName: 'IOWA',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotFull,
    sundayPickupTime: slotFull,
  },
  {
    stateName: 'NEBRASKA',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotFull,
    sundayPickupTime: slotFull,
  },
  {
    stateName: 'Colorado',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotFull,
    sundayPickupTime: slotFull,
  },
  {
    stateName: 'Kansas',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotFull,
    sundayPickupTime: slotFull,
  },
  {
    stateName: 'Missouri',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotFull,
    sundayPickupTime: slotFull,
  },
  {
    stateName: 'Tennessee',
    mondayPickupTime: slotNone,
    tuesdayPickupTime: slotNone,
    wednesdayPickupTime: slotNone,
    thursdayPickupTime: slotNone,
    fridayPickupTime: slotNone,
    saturdayPickupTime: slotFull,
    sundayPickupTime: slotFull,
  },
];
